#!/usr/bin/env node
/*
 * Injects the header splash's animation layer into a raw Figma export.
 *
 *     node tools/qm-splash/animate.mjs [input.svg]
 *
 * The splash is used as a CSS `background-image`, which means the browser loads it in a
 * sandboxed mode: no scripting inside the file, and no way for the page's stylesheet or
 * quantum.js to reach in. So every moving part has to be declarative CSS living inside the
 * SVG itself — including the reduced-motion guard, which cannot be inherited from the site.
 *
 * Run it again after any re-export from Figma. It is idempotent: it strips its own previous
 * output first, matches the curves it animates by their path data rather than by position in
 * the file, and throws if any anchor has gone missing rather than silently shipping a static
 * splash. See README.md.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const OUT = 'src/assets/img/qm/qm-splash-lg.svg';
const IN = process.argv[2] ?? OUT;

const BEGIN = '<!-- BEGIN generated by tools/qm-splash/animate.mjs -->';
const END = '<!-- END generated by tools/qm-splash/animate.mjs -->';

/* ── anchors ───────────────────────────────────────────────────────────────────────────
   Each curve is identified by the opening of its `d`, which is stable across re-exports so
   long as the artwork itself doesn't move. Blackbody curves are ordered hottest first, so
   the stagger runs down the temperature series rather than in export order. */
const CURVES = [
    { cls: 'qms-bb qms-bb-1', d: 'M21.4424 444', what: 'blackbody 5000 K' },
    { cls: 'qms-bb qms-bb-2', d: 'M29.0215 444', what: 'blackbody 4000 K' },
    { cls: 'qms-bb qms-bb-3', d: 'M36.6006 444', what: 'blackbody 3000 K' },
    { cls: 'qms-bb qms-bb-4', d: 'M66.916 444', what: 'blackbody 2000 K' },
    /* Figma starts this loop just right of the plot's origin, so the sweep grew out of the
       middle of the picture. It is closed, so re-rooting it at its leftmost vertex moves the
       anchor without altering a single pixel of the shape. Its partner already begins at
       x = 400 — the left edge — so only this one needs it. */
    /* Anchored on an interior segment, not on the `M`, precisely because re-rooting moves the
       `M`. This one is the segment that *arrives* at the leftmost vertex, so it survives
       verbatim and is unique in the file either way round. */
    { cls: 'qms-fx qms-fx-1', d: 'C403 350.834 400 341.4 400 333', what: 'forward-extinction, in phase', reroot: true },
    { cls: 'qms-fx qms-fx-2', d: 'M400 332', what: 'forward-extinction, π/2 out of phase' },
];

/* Re-roots a closed all-cubic path at its leftmost on-curve point. Figma emits these as
   `M p0 C … C … Z`, so the on-curve points are p0 plus each C's final point, and rotating the
   segment list is a pure relabelling: same geometry, same direction, different seam. That is
   what lets `stroke-dashoffset` grow the curve from the left. Doing it here rather than by
   hand is the point — a re-export brings Figma's seam back, and this puts it away again. */
function rerootClosedPath(d) {
    const m = d.match(/^M\s*(-?[\d.]+)[\s,]+(-?[\d.]+)([\s\S]*?)Z\s*$/);
    if (!m) return null;                                // not a shape we know how to re-root
    const segs = m[3].match(/C[^C]*/g);
    if (!segs) return null;

    /* Segments are carried as *verbatim* text rather than reparsed and reprinted. That keeps
       every coordinate byte-identical, so the anchor below still matches on the next run and
       re-rooting stays idempotent — reprinting numbers would quietly rewrite the file on every
       build and defeat the "only write when changed" guard. */
    const endOf = (seg) => seg.match(/-?[\d.]+/g).slice(4, 6).map(Number);
    const pointAt = (i) => (i < 0 ? [Number(m[1]), Number(m[2])] : endOf(segs[i]));

    // The final segment closes back onto the M, so it is the same point — skip it.
    let best = -1;
    for (let i = 0; i < segs.length - 1; i++) if (pointAt(i)[0] < pointAt(best)[0]) best = i;
    if (best === -1) return d;                          // already anchored at the leftmost point

    const head = pointAt(best);
    return `M${head[0]} ${head[1]}` + segs.slice(best + 1).concat(segs.slice(0, best + 1)).join('') + 'Z';
}

/* The Bloch sphere's outline is four bezier arcs, so its on-curve points give the centre and
   radius exactly. The equator's y-radius is read off the dashed ellipse rather than assumed:
   it comes back as 1/√3 of the x-radius, i.e. a true 35.26° isometric tilt, which is why the
   orbit below is a plain rotation inside a `scale(1 ry/rx)` group. */
function blochGeometry(svg) {
    const outline = svg.match(/<path d="M93\.9997 186\.098[^"]*"/);
    const equator = svg.match(/<path d="(M150\.638 73\.2997[^"]*)" stroke="#333333"/);
    if (!outline || !equator) throw new Error('Bloch sphere outline or equator not found');
    const n = equator[1].match(/-?\d+\.?\d*/g).map(Number);
    const ys = n.filter((_, i) => i % 2);
    const xs = n.filter((_, i) => !(i % 2));
    const cx = (Math.max(...xs) + Math.min(...xs)) / 2;
    const cy = (Math.max(...ys) + Math.min(...ys)) / 2;
    const rx = (Math.max(...xs) - Math.min(...xs)) / 2;
    const ry = (Math.max(...ys) - Math.min(...ys)) / 2;
    return { cx, cy, rx, ry, k: ry / rx };
}

/* ── the amplitude spiral ───────────────────────────────────────────────────────────────
   The top-right panel is a complex wave packet drawn in 3-D: 108 white beads on a helix
   winding around the x axis, plus its two shadows — 108 grey beads on the Re plane and 108
   on the Im plane. Rotating the helix about its axis is not a 2-D transform, so the 3-D
   structure has to be recovered from the flat artwork before anything can move.

   It recovers exactly, because the figure was plotted rather than drawn: the projection is a
   true linear map, so pairing each helix bead with its two shadows gives the Re and Im
   components directly. Everything below is measured at inject time rather than written down,
   so a re-export with different studio settings re-derives itself. */

const SPIRAL = { X0: 620, X1: 942, Y1: 250, WHITE: 'white', GREY: '#D2D2D2' };

function beadCentres(svg, fill) {
    const out = [];
    for (const m of svg.matchAll(/<path[^>]*?\/>/g)) {
        const tag = m[0];
        if (!tag.includes(`fill="${fill}"`)) continue;
        const d = tag.match(/\bd="([^"]*)"/);
        if (!d) continue;
        const n = d[1].match(/-?\d+\.?\d*/g).map(Number);
        const xs = n.filter((_, i) => !(i % 2)), ys = n.filter((_, i) => i % 2);
        const c = [(Math.min(...xs) + Math.max(...xs)) / 2, (Math.min(...ys) + Math.max(...ys)) / 2];
        if (c[0] > SPIRAL.X0 && c[0] < SPIRAL.X1 && c[1] < SPIRAL.Y1) out.push({ c, tag });
    }
    return out;
}

/* The direction from a shadow to its bead is the same for all 108 pairs, so it shows up as a
   spike in the histogram of every white-to-grey angle. Finding it that way needs no guess
   about which way the axes point — which matters, since the studio's view settings drift. */
function dominantDirection(whites, greys) {
    const bins = new Map();
    for (const w of whites) for (const g of greys) {
        const a = Math.atan2(w.c[1] - g.c[1], w.c[0] - g.c[0]) * 180 / Math.PI;
        const k = Math.round(((a % 360) + 360) % 360 * 10);
        bins.set(k, (bins.get(k) || 0) + 1);
    }
    let bk = 0, bv = -1;
    for (const [k, v] of bins) if (v > bv) { bv = v; bk = k; }
    const near = [...bins].filter(([k]) => Math.abs(k - bk) <= 15);
    const tot = near.reduce((s, [, v]) => s + v, 0);
    const ang = near.reduce((s, [k, v]) => s + k * v, 0) / tot / 10 * Math.PI / 180;
    return { u: [Math.cos(ang), Math.sin(ang)], hits: bv };
}

/* ⚠ Match the whole cloud at once as a bijection — never each bead to its own nearest.
   Every helix bead has exactly one shadow in each plane, but along the chain several shadows
   line up almost as well as the right one, so independent nearest-neighbour hands the same
   shadow to two beads and leaves another unclaimed. Only a handful of the 108 go wrong, and
   the damage does not look like a pairing bug: a bead with the wrong shadow gets the wrong
   Im component, which moves its computed point on the axis, which sorts it into the wrong
   slot — so whole runs of the chain come out shifted by one and the fit sits at 2.0u instead
   of 0.03u. Claiming the closest pairs first, each bead and shadow once, removes the ambiguity. */
function matchOneToOne(whites, greys, u0) {
    const once = (u) => whites.map((w) => {
        let best = null;
        for (const g of greys) {
            const v = [w.c[0] - g.c[0], w.c[1] - g.c[1]];
            if (v[0] * u[0] + v[1] * u[1] < -1) continue;
            const perp = Math.abs(v[0] * -u[1] + v[1] * u[0]);
            if (!best || perp < best.perp) best = { g, perp };
        }
        return best;
    });

    /* ⚠ Refine the direction against the pairing it produces, and iterate. Reading it once off
       the angle histogram lands within about 0.02 degrees, which sounds ample and is not: where
       the packet is widest, several shadows sit almost equally close to the ray, so a hundredth
       of a degree flips which one wins. A wrong shadow gives that bead the wrong component,
       which moves its computed point on the axis, which re-sorts it — so runs of the chain come
       out shifted by one and the fit sits at 2.9u instead of 0.03u, looking nothing like a
       pairing fault. Two or three passes converge and it stops mattering. */
    let u = u0, m = once(u);
    for (let pass = 0; pass < 8; pass++) {
        if (m.some((x) => !x)) return null;
        let sx = 0, sy = 0;
        for (let i = 0; i < whites.length; i++) {
            sx += whites[i].c[0] - m[i].g.c[0];
            sy += whites[i].c[1] - m[i].g.c[1];      // sum raw, so long offsets carry more weight
        }
        const L = Math.hypot(sx, sy);
        if (!L) return null;
        const un = [sx / L, sy / L];
        const moved = Math.hypot(un[0] - u[0], un[1] - u[1]);
        u = un; m = once(u);
        if (moved < 1e-12) break;
    }
    return m;
}

/* Least squares for the two plane offsets, given a trial (rho, spheres-per-cycle, phase).
   The constraint is only that the phase advances linearly along the chain — the envelope is
   left completely free, which is what makes this robust to the packet shape. */
function offsetsFor(A, B, dphi, ph0) {
    /* The condition is (b - b0)cos = rho (a - a0) sin at every bead. Expanded, that is linear
       in the three unknowns (rho, b0, rho*a0) — so the scale ratio does not need searching at
       all, which is what makes this converge. Searching it alongside the phase was what kept
       landing the fit in a false minimum. */
    const M = [[0, 0, 0], [0, 0, 0], [0, 0, 0]], V = [0, 0, 0];
    for (let i = 0; i < A.length; i++) {
        const p = ph0 + i * dphi, c = Math.cos(p), s = Math.sin(p);
        const r = [-A[i] * s, -c, s], rhs = -B[i] * c;
        for (let x = 0; x < 3; x++) { for (let y = 0; y < 3; y++) M[x][y] += r[x] * r[y]; V[x] += r[x] * rhs; }
    }
    // 3x3 Gaussian elimination with partial pivoting.
    const m = M.map((row, i) => [...row, V[i]]);
    for (let col = 0; col < 3; col++) {
        let piv = col;
        for (let r = col + 1; r < 3; r++) if (Math.abs(m[r][col]) > Math.abs(m[piv][col])) piv = r;
        if (Math.abs(m[piv][col]) < 1e-12) return null;
        [m[col], m[piv]] = [m[piv], m[col]];
        for (let r = 0; r < 3; r++) {
            if (r === col) continue;
            const k = m[r][col] / m[col][col];
            for (let c2 = col; c2 < 4; c2++) m[r][c2] -= k * m[col][c2];
        }
    }
    const rho = m[0][3] / m[0][0], b0 = m[1][3] / m[1][1], a0 = (m[2][3] / m[2][2]) / rho;
    if (!(rho > 0.3 && rho < 3)) return null;
    let res = 0;
    for (let i = 0; i < A.length; i++) {
        const p = ph0 + i * dphi;
        res += ((B[i] - b0) * Math.cos(p) - rho * (A[i] - a0) * Math.sin(p)) ** 2;
    }
    return { rms: Math.sqrt(res / A.length), a0, b0, rho };
}

function spiralGeometry(svg) {
    const W = beadCentres(svg, SPIRAL.WHITE), G = beadCentres(svg, SPIRAL.GREY);
    if (W.length < 40 || G.length < 2 * W.length - 4) return null;

    // Split the shadows by which side of the helix's own principal axis they fall on.
    const mx = W.reduce((s, p) => s + p.c[0], 0) / W.length, my = W.reduce((s, p) => s + p.c[1], 0) / W.length;
    let sxx = 0, sxy = 0, syy = 0;
    for (const p of W) { sxx += (p.c[0] - mx) ** 2; sxy += (p.c[0] - mx) * (p.c[1] - my); syy += (p.c[1] - my) ** 2; }
    const th = 0.5 * Math.atan2(2 * sxy, sxx - syy), ex = Math.cos(th), ey = Math.sin(th);
    const side = (p) => (p.c[0] - mx) * -ey + (p.c[1] - my) * ex;
    const cRe = G.filter((p) => side(p) < 0), cIm = G.filter((p) => side(p) >= 0);
    if (Math.abs(cRe.length - cIm.length) > 2) return null;

    const dIm = dominantDirection(W, cRe);   // helix - Re shadow lies along the Im axis
    const dRe = dominantDirection(W, cIm);   // helix - Im shadow lies along the Re axis
    const uIm = dIm.u, uRe = dRe.u;

    const mRe = matchOneToOne(W, cRe, uIm), mIm = matchOneToOne(W, cIm, uRe);
    const rows = [];
    for (let wi = 0; wi < W.length; wi++) {
        const w = W[wi], pRe = mRe[wi], pIm = mIm[wi];
        if (!pRe || !pIm || pRe.perp > 2 || pIm.perp > 2) return null;
        const a = (w.c[0] - pIm.g.c[0]) * uRe[0] + (w.c[1] - pIm.g.c[1]) * uRe[1];
        const b = (w.c[0] - pRe.g.c[0]) * uIm[0] + (w.c[1] - pRe.g.c[1]) * uIm[1];
        /* Order the chain by each bead's own point on the axis, never by the bead itself: the
           helix swings +-26u about the axis, so projecting the beads onto it is not monotone
           and silently interleaves the chain. Subtracting the Re and Im components lands every
           bead on a line — collinear to 0.03u — along which the ordering is exact. */
        rows.push({ w, re: pRe.g, im: pIm.g, a, b, ax: (w.c[0] - a * uRe[0] - b * uIm[0]) * ex + (w.c[1] - a * uRe[1] - b * uIm[1]) * ey });
    }
    rows.sort((p, q) => p.ax - q.ax);
    const A = rows.map((r) => r.a), B = rows.map((r) => r.b);

    // Coarse sweep, then three rounds of narrowing around the best point.
    let best = null;
    const consider = (spc, ph0) => {
        const r = offsetsFor(A, B, 2 * Math.PI / spc, ph0);
        if (r && (!best || r.rms < best.rms)) best = { ...r, spc, ph0 };
    };
    for (let spc = 14; spc <= 22; spc += 0.01)
        for (let k = 0; k < 240; k++) consider(spc, k * 2 * Math.PI / 240);
    let dS = 0.01, dP = 2 * Math.PI / 240;
    for (let pass = 0; pass < 4; pass++) {
        const b0 = best;
        for (let j = -10; j <= 10; j++) for (let k = -10; k <= 10; k++)
            consider(b0.spc + j * dS / 10, b0.ph0 + k * dP / 10);
        dS /= 10; dP /= 10;
    }
    if (best.rms > 0.5) return null;   // the model did not take; leave the panel alone

    const { rho, a0, b0, ph0 } = best;
    const dphi = 2 * Math.PI / best.spc;
    const marks = [];
    rows.forEach((r, i) => {
        const ta = r.a - a0, tb = r.b - b0;
        const R = Math.hypot(ta, tb / rho), psi = Math.atan2(tb / rho, ta);
        const cx = r.w.c[0] - ta * uRe[0] - tb * uIm[0];      // the point on the x axis
        const cy = r.w.c[1] - ta * uRe[1] - tb * uIm[1];
        // e1 and e2 are where one unit of Re and of Im land on screen, as complex numbers.
        const e1 = { x: uRe[0], y: uRe[1] }, e2 = { x: rho * uIm[0], y: rho * uIm[1] };
        const mul = (z, k) => ({ x: z.x * k, y: z.y * k });
        const add = (z, w) => ({ x: z.x + w.x, y: z.y + w.y });
        const mi = (z) => ({ x: z.y, y: -z.x });              // multiply by -i
        /* Anchor each orbit on the element's *own* drawn position rather than on the axis point
           plus a plane offset. Algebraically the two agree, but a shadow sits a few hundredths
           of a unit off its ray in the artwork, and going via the offset spends that error as a
           visible jump at rest. Subtracting the rest displacement instead makes every one of
           the 324 reproduce its own pixel exactly, which is what the assertion downstream then
           has the right to demand. */
        marks.push(
            { tag: r.w.tag, at: r.w.c, cx, cy, R, psi, P: mul(add(e1, mi(e2)), R / 2), Q: mul(add(e1, mi(mul(e2, -1))), R / 2) },
            { tag: r.re.tag, at: r.re.c, cx: r.re.c[0] - ta * uRe[0], cy: r.re.c[1] - ta * uRe[1], R, psi, P: mul(e1, R / 2), Q: mul(e1, R / 2) },
            { tag: r.im.tag, at: r.im.c, cx: r.im.c[0] - tb * uIm[0], cy: r.im.c[1] - tb * uIm[1], R, psi, P: mul(mi(e2), R / 2), Q: mul(mi(mul(e2, -1)), R / 2) },
        );
    });
    return { marks, fit: best, uRe, uIm };
}

/* Under rotation a bead travels an *ellipse*, because the two projected axes are neither
   perpendicular nor the same length. Putting the bead inside that shear would squash it and
   make it wobble as it turned. But every ellipse is the sum of two counter-rotating phasors,
   and nested rotate+translate produces exactly that sum:

       translate(c) rotate(t+psi+argP) translate(|P|) rotate(-2(t+psi)+argQ-argP) translate(|Q|)

   lands on c + P*e^(i(t+psi)) + Q*e^(-i(t+psi)) exactly, and the bead's own net transform is a
   pure rotation — so a circle stays a circle. The shadows are the degenerate case where
   |P| = |Q|, which is why one construction serves the helix and both projections. */
function spiralMarkup(svg, geo) {
    const deg = (r) => (r * 180 / Math.PI);
    const f = (n) => String(Number(n.toFixed(3)));
    let worst = 0;
    for (const m of geo.marks) {
        const argP = Math.atan2(m.P.y, m.P.x), argQ = Math.atan2(m.Q.y, m.Q.x);
        const p = Math.hypot(m.P.x, m.P.y), q = Math.hypot(m.Q.x, m.Q.y);
        const Aang = deg(m.psi + argP), Bang = deg(-2 * m.psi + argQ - argP);

        // Assert the construction reproduces the artwork at t = 0, before trusting it.
        const t1 = m.psi + argP, t2 = -2 * m.psi + argQ - argP;
        const ix = q * Math.cos(t2) + p, iy = q * Math.sin(t2);
        const px = m.cx + ix * Math.cos(t1) - iy * Math.sin(t1);
        const py = m.cy + ix * Math.sin(t1) + iy * Math.cos(t1);
        worst = Math.max(worst, Math.hypot(px - m.at[0], py - m.at[1]));

        const wrapped =
            `<g class="qms-orbit" transform="translate(${f(m.cx)} ${f(m.cy)})">` +
            `<g class="qms-sp1">` +
            `<g transform="rotate(${f(Aang)}) translate(${f(p)} 0)">` +
            `<g class="qms-sp2">` +
            `<g transform="rotate(${f(Bang)}) translate(${f(q)} 0) translate(${f(-m.at[0])} ${f(-m.at[1])})">` +
            m.tag +
            `</g></g></g></g></g>`;
        svg = svg.replace(m.tag, wrapped);
    }
    return { svg, worst };
}

/* ── the shape of a sweep ───────────────────────────────────────────────────────────────
   Fractions of one cycle: how long a curve takes to draw itself in, how long it then holds
   fully drawn, and how long it takes to slide off. Whatever is left over is the gap, where
   the stage stands empty until the cycle comes round again.

   The stagger lives here too, as a fraction of the cycle rather than an absolute time, because
   it and the hold have to agree. Leave hold out and it is derived as (count - 1) * stagger,
   which is the value that puts a family in lock-step: the instant the last curve finishes
   entering is the instant the first begins to leave. Spend the rest of the cycle on enter and
   exit and there is no gap either, so the loop runs continuously — in, out, in — with nothing
   ever standing still. Give hold a value to break that deliberately, as the extinction pair
   does with hold: 0, where each lobe turns around the moment it arrives.

   ⚠ The stagger had to move here rather than stay a CSS custom property. CSS could hold it
   perfectly well, but a keyframe selector is a literal percentage and cannot read var(), so
   the hold could never be written in terms of it — and the two would silently fall out of
   step the first time either was tuned. Cycle length stays in CSS; choreography lives here. */
const SWEEP = {
    /* 'sweep' draws a curve on and slides it off; 'march' leaves it permanently on the page as
       a dashed line whose dashes travel along it. The homepage card animates the extinction
       pair the second way, one curve against the other, and this is that effect brought over —
       see familyRules below for why it is not just a different set of keyframes. */
    bb: { mode: 'sweep', name: 'qmsSweepBB', count: 4, stagger: 0.125, enter: 0.3125, exit: 0.3125, timing: 'linear' },
    fx: { mode: 'march', name: 'qmsMarchFX', count: 2, drawn: 0.8, timing: 'linear' },
};

// The class list above is what actually gets animated, so disagreeing about how many there are
// would show up as one curve that never moves rather than as an error.
for (const [fam, s] of Object.entries(SWEEP)) {
    const n = CURVES.filter((c) => c.cls.startsWith(`qms-${fam} `)).length;
    if (n !== s.count) throw new Error(`SWEEP.${fam}.count is ${s.count} but ${n} curves carry that class`);
}

const sweepHold = (s) => (s.hold ?? (s.count - 1) * s.stagger);

function sweepKeyframes(name, s) {
    const hold = sweepHold(s);
    const gap = 1 - s.enter - hold - s.exit;
    if (gap < -1e-9) throw new Error(`${name}: enter + hold + exit come to more than one cycle`);
    const at = (x) => `${Number((x * 100).toFixed(4))}%`;
    const stops = [
        [at(0), '1px'],                                   // off-stage, about to enter
        [at(s.enter), '0px'],                             // fully drawn
        [at(s.enter + hold), '0px'],                      // ...still fully drawn: the hold
        [at(s.enter + hold + s.exit), '-1px'],            // slid off the far end
    ];
    if (gap > 1e-9) stops.push([at(1), '-1px']);
    /* Collapse stops that land on the same percentage. A zero hold puts the two 0px stops on
       one selector and a zero gap puts the two -1px stops on 100%; duplicates are legal CSS
       and the later one simply wins, so this never misrenders — it just emits keyframes that
       read as a mistake, which is worse in a file people are meant to tune by hand. */
    const uniq = stops.filter(([q], i) => i === 0 || q !== stops[i - 1][0]);
    return `@keyframes ${name} {\n`
        + uniq.map(([q, v]) => `    ${q.padStart(8)} { stroke-dashoffset: ${v.padStart(4)}; }`).join('\n')
        + `\n}`;
}

// Delays are a fraction of the cycle, so retiming a family rescales its choreography with it.
function sweepDelays(cls, s, cycle) {
    return Array.from({ length: s.count }, (_, i) =>
        `.${cls}-${i + 1} { animation-delay: calc(var(${cycle}) * ${Number((i * s.stagger).toFixed(6))}); }`
    ).join('\n');
}

function familyRules(fam, s) {
    const cls = `qms-${fam}`, cycle = `--qms-${fam}-cycle`;

    if (s.mode === 'march') {
        /* `drawn` is the fraction of the curve visible at any moment, so what travels round the
           curve is the *gap*. It has to be a fraction rather than the homepage's absolute 50
           user units, even though both files draw this artwork at identical scale — see below.

           The offset covers one whole path length per cycle, which with pathLength="1" is
           exactly 1, so the pattern lands back on itself and the loop is seamless. */
        return `@keyframes ${s.name} {
    from { stroke-dashoffset: 1px; }
      to { stroke-dashoffset: 0px; }
}

.${cls} {
    stroke-dasharray: ${s.drawn}px, ${Number((1 - s.drawn).toFixed(4))}px;
    animation: ${s.name} var(${cycle}) ${s.timing} infinite;
}

/* The two curves march against each other, which is the whole point of the effect: they are the
   in-phase and the quarter-out-of-phase component, and sending them opposite ways says so. The
   homepage writes two mirrored keyframe sets for this; one set played backwards is the same
   motion and cannot drift out of step with its twin. */
.${cls}-2 { animation-direction: reverse; }`;
    }

    return `${sweepKeyframes(s.name, s)}

.${cls} {
    stroke-dasharray: 1px 1px;
    stroke-dashoffset: 1px;
    animation: ${s.name} var(${cycle}) ${s.timing} infinite;
}

${sweepDelays(cls, s, cycle)}`;
}

/* ⚠ The CSS is wrapped in CDATA because an SVG is parsed as XML, not HTML: a bare `<` in a
   stylesheet — `4 × stagger < the hold`, `<length>` in a comment — opens a tag and takes the
   whole document with it. As a background-image that is fatal and silent; the browser drops
   the image and the header renders as a bare gradient, which looks like the URL is wrong. */
const STYLE = (g) => `${BEGIN}
<style><![CDATA[
/* ══ DIALS ══════════════════════════════════════════════════════════════════════════════
   Everything tweakable is here. Durations are the honest ones — this file animates in real
   time from page load and has no way to be paused, seeked or synced to the article, so
   prefer slow: the splash is texture behind a headline, not a widget. */
svg {
    /* Blackbody curves (bottom left): one cycle is the whole life of a single curve — draw in,
       hold, slide off. Forward-extinction lobes (bottom middle): one cycle is one dash-and-gap
       of travel, so the pattern lands back on itself; 10s is the homepage card's own value.

       Neither family's *shape* is here — the stagger, the enter/hold/exit split, the dash size
       — because those are fractions or lengths that have to stay in step with each other. They
       live in SWEEP in animate.mjs. Retiming a family here rescales its whole choreography. */
    --qms-bb-cycle:   4s;
    --qms-fx-cycle:  10s;

    /* Bloch precession (top left). --qms-wobble is deliberately a whole multiple of
       --qms-spin (3 laps), so the pair repeats exactly rather than drifting; make it a
       non-multiple if you want it never to quite repeat. */
    --qms-spin:            3s;
    --qms-wobble:         10s;
    --qms-wobble-amp:      45deg;  /* how far the orbit's axis nods; an ANGLE, see below */
    --qms-dot-r:            2px;
    --qms-back-opacity:     0.5;  /* the marker while it is behind the sphere */
    --qms-vector-opacity:   1.0; /* 0 hides the state vector and leaves a bare particle */

    /* Amplitude spiral (top right) — one turn of the wave packet about its own axis. This is
       a phase rotation, so it is the slowest thing on the card by some way: it is the only
       animation here that a reader could mistake for the physics being fast. */
    --qms-spiral:         3s;
}

/* ══ SWEEP ══════════════════════════════════════════════════════════════════════════════
   Each curve carries pathLength="1", so progress is a unit regardless of its real length and
   nothing has to be measured. Offset runs 1 → 0 → -1: at 1 the dash sits entirely in the
   gap (invisible), at 0 it covers the path, at -1 it has slid past the far end. That is one
   monotonic move, so the loop closes seamlessly — no reversal, and -1 and +1 look identical.

   ⚠ The px is mandatory. stroke-dashoffset takes a <length>; a bare 0.42 is dropped silently
   and the animation simply never moves.

   The stops below are generated from the SWEEP shape in animate.mjs — enter, hold, leave, gap.
   Edit them there, not here, or the next run overwrites them. */
${familyRules('bb', SWEEP.bb)}

${familyRules('fx', SWEEP.fx)}

/* ══ PRECESSION ═════════════════════════════════════════════════════════════════════════
   Three nested groups, because a CSS transform *replaces* a transform attribute rather than
   composing with it — so every animated transform needs a group of its own, and the static
   placement lives on separate groups that CSS never touches.

   Order matters: the squash is outside the rotation, so a circular orbit of radius rx is
   projected into the equator ellipse. Put it inside and you get a rotating ellipse instead. */
.qms-precess { animation: qmsPrecess var(--qms-spin) linear infinite,
                          qmsDepth   var(--qms-spin) linear infinite; }
.qms-wobble  { animation: qmsWobble  var(--qms-wobble) cubic-bezier(0.37, 0, 0.63, 1) infinite; }

@keyframes qmsPrecess { to { transform: rotate(360deg); } }

/* ⚠ The wobble has to be a *linear* transform — a rotation, not a translation. The vector is a
   single line running from this group's origin (the sphere's centre) out to the tip, so
   anything that moves the tip moves the tail along with it. A rotation fixes the origin, which
   pins the tail to the centre and lets only the tip travel; a translate slid the whole vector,
   centre and all, and that is what made it look unmoored.

   It also reads as the precession axis nodding, which is the honest thing for a spin vector to
   do. Any origin-fixing transform would work — a scale included — but on a Bloch sphere the
   vector is a unit, so letting its length breathe would say something false about the state.

   ⚠ transform-origin is 0 0 on SVG elements, not 50% 50% as it is in HTML. That is why this
   needs no transform-origin declaration, and why copying the rule into HTML would break it. */
/* A true sinusoid: fastest crossing the equator, momentarily still at each extreme — which is
   what nutation actually looks like, and the opposite of what a keyframe list wants to do.

   The trick is that the *extremes* are the keyframes and the equator is not. A timing function
   applies to every segment, so any stop you write is a place the motion stops; putting one at
   rotation 0 parks the orbit on the equator twice a cycle, which is exactly the dwell this
   replaces. With only the turning points as stops, the eased segment between them IS the
   half-cycle. cubic-bezier(.37,0,.63,1) is easeInOutSine, so this evaluates to
   -amp * cos(2*pi*t) to within a fraction of a degree — verified by sampling, not by eye. */
@keyframes qmsWobble {
      0% { transform: rotate(calc(var(--qms-wobble-amp) * -1)); }
     50% { transform: rotate(var(--qms-wobble-amp)); }
    100% { transform: rotate(calc(var(--qms-wobble-amp) * -1)); }
}

/* Half a lap is spent behind the sphere. In SVG's y-down space the *near* half of the
   equator is the lower one, so the marker dims through the second half of the rotation.
   The crossings are at the silhouette edge, where a hard cut would be physically right —
   this ramps over ~10% of a lap anyway, because a hard cut reads as a flicker. */
@keyframes qmsDepth {
      0% { opacity: 1; }
     45% { opacity: 1; }
     55% { opacity: var(--qms-back-opacity); }
     95% { opacity: var(--qms-back-opacity); }
    100% { opacity: 1; }
}

.qms-vector   { stroke: black; stroke-width: 1.2; opacity: var(--qms-vector-opacity); }
.qms-particle { fill: black; r: var(--qms-dot-r); }

/* ══ AMPLITUDE SPIRAL ═══════════════════════════════════════════════════════════════════
   Two shared rotations, one at the phase rate and one at minus twice it. Every bead's own
   phase is baked into a static rotate attribute beside these, so there are no per-bead
   delays and no per-bead keyframes — 324 beads share exactly these two animations.

   At rotation zero the construction reproduces the artwork bead for bead, which is why the
   reduced-motion case below is simply "no animation": it parks on the frame Figma drew. */
.qms-sp1 { animation: qmsSpiral1 var(--qms-spiral) linear infinite; }
.qms-sp2 { animation: qmsSpiral2 var(--qms-spiral) linear infinite; }

@keyframes qmsSpiral1 { to { transform: rotate(360deg); } }
@keyframes qmsSpiral2 { to { transform: rotate(-720deg); } }

/* ══ REDUCED MOTION ═════════════════════════════════════════════════════════════════════
   This block is the *only* reduced-motion guard there is. The page's stylesheet cannot
   reach into a background-image SVG, so the usual "guard it twice" rule has nothing to hook
   into — if this is deleted, the splash keeps moving for everybody.

   Kill everything with one blanket rule rather than naming the classes. Nothing in this header
   is motion-that-conveys-state — it is texture behind a headline — so there is no case for
   keeping any of it, and an enumerated list is a trap: the next animation added here would keep
   running for anyone who asked for stillness, and nothing would catch it.

   The !important is load-bearing. A universal selector has zero specificity, so without it
   every one of the rules above wins and this block does nothing at all.

   Only the dash restore is left, and it has to be: with the sweep gone the curves would sit at
   their base stroke-dashoffset of 1px, which is the invisible end of the sweep, so the two
   panels would come up empty rather than still. Everything else already rests on the frame
   Figma drew — rotation zero reproduces the artwork bead for bead. */
@media (prefers-reduced-motion: reduce) {
    * {
        animation: none !important;
    }

    .qms-bb,
    .qms-fx {
        stroke-dasharray: none;
        stroke-dashoffset: 0px;
    }
}
]]></style>
${END}`;

const MARKER = (g) => `${BEGIN}
<g transform="translate(${g.cx} ${g.cy})">
    <g class="qms-wobble">
        <g transform="scale(1 ${g.k.toFixed(5)})">
            <g class="qms-precess">
                <line class="qms-vector" x1="0" y1="0" x2="${g.rx.toFixed(3)}" y2="0" vector-effect="non-scaling-stroke"/>
                <circle class="qms-particle" cx="${g.rx.toFixed(3)}" cy="0" r="4"/>
            </g>
        </g>
    </g>
</g>
${END}`;

/* ── run ───────────────────────────────────────────────────────────────────────────────── */

/* Returns { changed } and only touches the file when the bytes actually differ. That matters:
   `.eleventy.js` calls this on every build, and the output lives under a watched passthrough
   directory — writing unconditionally would re-trigger the watcher and spin forever. */
export function injectSplashAnimation({ input = OUT, output = OUT } = {}) {
    let svg = readFileSync(input, 'utf8');
    const before = svg.length;

    /* Strip a previous run so this is safe to re-apply to its own output. The spiral wraps
       each bead in five groups, so unwrapping is the inverse: the original element is the
       only thing inside, verbatim, which is why it is carried here rather than rebuilt from
       the orbit maths — reconstruction would have to be bit-exact to stay idempotent. */
    svg = svg.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}\\n?`, 'g'), '');
    svg = svg.replace(/<g class="qms-orbit"[^>]*>(?:<g[^>]*>){4}(<path[^>]*?\/>)<\/g><\/g><\/g><\/g><\/g>/g, '$1');
    svg = svg.replace(/ class="qms-[^"]*"/g, '').replace(/ pathLength="1"/g, '');

    for (const { cls, d, what, reroot } of CURVES) {
        // `contains`, not `starts with` — a re-rooted path no longer begins with its old `M`.
        const esc = d.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const whole = new RegExp(`<path((?:(?!/>)[^>])*?)d="([^"]*${esc}[^"]*)"`);
        const found = svg.match(whole);
        if (!found) throw new Error(`anchor for ${what} (d="${d}…") not found — did the export change?`);
        // null means "couldn't parse it"; returning the input unchanged means "already correct".
        const rerooted = reroot ? rerootClosedPath(found[2]) : found[2];
        if (reroot && rerooted === null) console.warn(`  ! ${what}: could not re-root; the sweep will start wherever Figma put the seam`);
        const data = rerooted ?? found[2];
        svg = svg.replace(whole, `<path class="${cls}" pathLength="1"$1d="${data}"`);
    }

    const spiral = spiralGeometry(svg);
    let spiralNote = 'not found — panel left static';
    if (spiral) {
        const r = spiralMarkup(svg, spiral);
        if (r.worst > 0.05) throw new Error(`spiral construction is off by ${r.worst.toFixed(3)}u at rest — it would not reproduce the artwork`);
        svg = r.svg;
        spiralNote = `${spiral.marks.length} beads, ${spiral.fit.spc.toFixed(3)} per cycle, ` +
            `Im/Re ${spiral.fit.rho.toFixed(3)}, fit RMS ${spiral.fit.rms.toFixed(4)}u, rest error ${r.worst.toFixed(4)}u`;
    }

    const geo = blochGeometry(svg);
    svg = svg.replace(/(<svg[^>]*>)/, `$1\n${STYLE(geo)}`);

    // The marker goes last inside the clip group, so it draws over the sphere's wireframe.
    const close = svg.lastIndexOf('</g>\n<defs>');
    if (close === -1) throw new Error('could not find the end of the clip group');
    svg = svg.slice(0, close) + MARKER(geo) + '\n' + svg.slice(close);

    /* Well-formedness, because the failure mode is silent: an XML parse error makes the browser
       drop the image entirely and the header renders as a bare gradient. Cheap structural checks
       beat shipping and finding out. */
    const css = svg.slice(svg.indexOf('<![CDATA[') + 9, svg.indexOf(']]></style>'));
    if (css.includes(']]>')) throw new Error('CSS closes its own CDATA section');
    const body = svg.replace(/<!\[CDATA\[[\s\S]*?\]\]>/g, '').replace(/<!--[\s\S]*?-->/g, '');
    const stray = body.match(/<(?![a-zA-Z/?!])/);
    if (stray) throw new Error(`stray "<" outside CDATA at offset ${stray.index} — the SVG will not parse`);

    const changed = !existsSync(output) || readFileSync(output, 'utf8') !== svg;
    if (changed) writeFileSync(output, svg);
    return { changed, geo, spiralNote, before, after: svg.length };
}

// Only report when run as a CLI; `.eleventy.js` imports the function and stays quiet.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    const { changed, geo, spiralNote, before, after } = injectSplashAnimation({ input: IN });
    console.log(`${IN} → ${OUT}${changed ? '' : ' (already up to date)'}`);
    const swept = CURVES.filter((c) => SWEEP[c.cls.split(' ')[0].slice(4)].mode !== 'march').length;
    console.log(`  ${CURVES.length} curves given pathLength + a class (${swept} swept, ${CURVES.length - swept} marching)`);
    console.log(`  Bloch orbit: centre (${geo.cx}, ${geo.cy}) rx ${geo.rx.toFixed(3)} tilt ${(Math.asin(geo.k) * 180 / Math.PI).toFixed(2)}°`);
    console.log(`  Spiral: ${spiralNote}`);
    console.log(`  ${before.toLocaleString()} → ${after.toLocaleString()} B`);
}
